package tcp_scanner

import (
	"fmt"
	"net"
	"strconv"
	"sync"
	"time"
)

func GetOpenPorts1(host string, maxPortNumber int) ([]int, error) { // TODO сейчас ошибку не выбрасываем. но  где она может быть?

	dialer := net.Dialer{
		Timeout: 10 * time.Second,
	}

	openPorts := make([]int, 0)

	var wg sync.WaitGroup

	for port := 1; port <= maxPortNumber; port++ {
		wg.Add(1)
		go func(j int) {
			defer wg.Done()
			conn, err := dialer.Dial("tcp", host+":"+strconv.Itoa(j))
			if err != nil {
				return
			}
			err = conn.Close()
			if err != nil {
				fmt.Println("Unexpected conn. closing error:", err.Error())
			}

			openPorts = append(openPorts, j)
		}(port)

	}
	wg.Wait()

	return openPorts, nil
}
